zion:
  stair_detection:
    ros__parameters:
      general:
        camera_topic: '/zedm/zed_node/rgb/image_rect_color'
        detection_topic_img: '/zion/stair_detection/detection_image'
        detection_topic_data: '/zion/stair_detection/detection'

      model: 
        device: cuda          # cuda | cpu
        model_path: 'best'    # relative path from env_clf_ros dir to the models dir
        trt: False            # use TensorRT
        conf: 0.7             # confidence threshold
                              # model will consider only predictions that are at least as the conf param and higher. 

/**:
    ros__parameters:
      allNodeCanSee: True